"""initial_schema

Revision ID: 512fbe0aa3a1
Revises: 
Create Date: 2025-12-25 05:06:45.335187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '512fbe0aa3a1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_versions',
    sa.Column('version_id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('version_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ticker_count', sa.Integer(), nullable=False),
    sa.Column('snapshot_count', sa.Integer(), nullable=False),
    sa.Column('date_range_start', sa.Date(), nullable=False),
    sa.Column('date_range_end', sa.Date(), nullable=False),
    sa.Column('data_hash', sa.String(length=64), nullable=False),
    sa.Column('filter_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('version_id'),
    sa.UniqueConstraint('version_name')
    )
    op.create_table('financial_snapshots',
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('snapshot_timestamp', sa.DateTime(), nullable=False),
    sa.Column('period_end_date', sa.Date(), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('frequency', sa.String(length=10), nullable=True),
    sa.Column('original_currency', sa.String(length=10), nullable=False),
    sa.Column('stored_currency', sa.String(length=10), nullable=False),
    sa.Column('fx_rate_to_usd', sa.Numeric(), nullable=True),
    sa.Column('total_revenue', sa.Numeric(), nullable=True),
    sa.Column('gross_profit', sa.Numeric(), nullable=True),
    sa.Column('ebitda', sa.Numeric(), nullable=True),
    sa.Column('operating_income', sa.Numeric(), nullable=True),
    sa.Column('net_income', sa.Numeric(), nullable=True),
    sa.Column('eps', sa.Numeric(), nullable=True),
    sa.Column('shares_outstanding', sa.Numeric(), nullable=True),
    sa.Column('float_shares', sa.Numeric(), nullable=True),
    sa.Column('total_debt', sa.Numeric(), nullable=True),
    sa.Column('total_cash', sa.Numeric(), nullable=True),
    sa.Column('total_assets', sa.Numeric(), nullable=True),
    sa.Column('free_cash_flow', sa.Numeric(), nullable=True),
    sa.Column('operating_cash_flow', sa.Numeric(), nullable=True),
    sa.Column('capex', sa.Numeric(), nullable=True),
    sa.Column('working_capital', sa.Numeric(), nullable=True),
    sa.Column('book_value', sa.Numeric(), nullable=True),
    sa.Column('profit_margins', sa.Numeric(), nullable=True),
    sa.Column('gross_margin', sa.Numeric(), nullable=True),
    sa.Column('operating_margin', sa.Numeric(), nullable=True),
    sa.Column('net_margin', sa.Numeric(), nullable=True),
    sa.Column('roe', sa.Numeric(), nullable=True),
    sa.Column('roa', sa.Numeric(), nullable=True),
    sa.Column('roic', sa.Numeric(), nullable=True),
    sa.Column('debt_to_equity', sa.Numeric(), nullable=True),
    sa.Column('current_ratio', sa.Numeric(), nullable=True),
    sa.Column('quick_ratio', sa.Numeric(), nullable=True),
    sa.Column('dividend_yield', sa.Numeric(), nullable=True),
    sa.Column('dividend_rate', sa.Numeric(), nullable=True),
    sa.Column('five_year_avg_div_yield', sa.Numeric(), nullable=True),
    sa.Column('audit_risk', sa.Integer(), nullable=True),
    sa.Column('board_risk', sa.Integer(), nullable=True),
    sa.Column('compensation_risk', sa.Integer(), nullable=True),
    sa.Column('beta', sa.Numeric(), nullable=True),
    sa.Column('shares_short', sa.Numeric(), nullable=True),
    sa.Column('shares_short_prior_month', sa.Numeric(), nullable=True),
    sa.Column('short_ratio', sa.Numeric(), nullable=True),
    sa.Column('held_percent_insiders', sa.Numeric(), nullable=True),
    sa.Column('held_percent_institutions', sa.Numeric(), nullable=True),
    sa.Column('full_time_employees', sa.Integer(), nullable=True),
    sa.Column('price_t0', sa.Numeric(), nullable=True),
    sa.Column('price_t_minus_1', sa.Numeric(), nullable=True),
    sa.Column('price_t_plus_1', sa.Numeric(), nullable=True),
    sa.Column('market_cap_t0', sa.Numeric(), nullable=True),
    sa.Column('data_quality_score', sa.Numeric(), nullable=True),
    sa.Column('validation_warnings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('ticker', 'snapshot_timestamp')
    )
    op.create_index('idx_snapshots_filing', 'financial_snapshots', ['filing_date'], unique=False)
    op.create_index('idx_snapshots_mcap', 'financial_snapshots', ['market_cap_t0'], unique=False)
    op.create_index('idx_snapshots_timestamp', 'financial_snapshots', ['snapshot_timestamp'], unique=False)
    op.create_table('fx_rates',
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('from_currency', sa.String(length=10), nullable=False),
    sa.Column('to_currency', sa.String(length=10), nullable=False),
    sa.Column('rate', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('rate_date', 'from_currency', 'to_currency')
    )
    op.create_table('raw_payloads',
    sa.Column('payload_id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('snapshot_timestamp', sa.DateTime(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('endpoint', sa.String(length=100), nullable=False),
    sa.Column('payload_body', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('payload_id')
    )
    op.create_index('idx_payloads_ticker_ts', 'raw_payloads', ['ticker', 'snapshot_timestamp'], unique=False)
    op.create_table('tickers',
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('original_currency', sa.String(length=10), nullable=True),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('ipo_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('data_version_snapshots',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('snapshot_timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticker', 'snapshot_timestamp'], ['financial_snapshots.ticker', 'financial_snapshots.snapshot_timestamp'], ),
    sa.ForeignKeyConstraint(['version_id'], ['data_versions.version_id'], ),
    sa.PrimaryKeyConstraint('version_id', 'ticker', 'snapshot_timestamp')
    )
    op.create_table('valuation_results',
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('snapshot_timestamp', sa.DateTime(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('predicted_mcap_mean', sa.Numeric(), nullable=False),
    sa.Column('predicted_mcap_std', sa.Numeric(), nullable=False),
    sa.Column('actual_mcap', sa.Numeric(), nullable=False),
    sa.Column('relative_error', sa.Numeric(), nullable=False),
    sa.Column('relative_std', sa.Numeric(), nullable=False),
    sa.Column('model_config_hash', sa.String(length=64), nullable=True),
    sa.Column('n_experiments', sa.Integer(), nullable=False),
    sa.Column('experiment_metadata', sa.JSON(), nullable=True),
    sa.Column('data_version_id', sa.UUID(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['data_version_id'], ['data_versions.version_id'], ),
    sa.PrimaryKeyConstraint('ticker', 'snapshot_timestamp', 'model_version')
    )
    op.create_index('idx_valuation_data_version', 'valuation_results', ['data_version_id'], unique=False)
    op.create_index('idx_valuation_error', 'valuation_results', ['relative_error'], unique=False)
    op.create_index('idx_valuation_model', 'valuation_results', ['model_version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_valuation_model', table_name='valuation_results')
    op.drop_index('idx_valuation_error', table_name='valuation_results')
    op.drop_index('idx_valuation_data_version', table_name='valuation_results')
    op.drop_table('valuation_results')
    op.drop_table('data_version_snapshots')
    op.drop_table('tickers')
    op.drop_index('idx_payloads_ticker_ts', table_name='raw_payloads')
    op.drop_table('raw_payloads')
    op.drop_table('fx_rates')
    op.drop_index('idx_snapshots_timestamp', table_name='financial_snapshots')
    op.drop_index('idx_snapshots_mcap', table_name='financial_snapshots')
    op.drop_index('idx_snapshots_filing', table_name='financial_snapshots')
    op.drop_table('financial_snapshots')
    op.drop_table('data_versions')
    # ### end Alembic commands ###
